>P1;2lw3_A
structureX:2lw3_A:52:A:140:A:::-1.00:-1.00
--------------HLTYEIFGPPGTVADISYFDVNSEPQRVDGAVLPWSLHITTNDAAVMGNIVAQGNSDSIGC
RITVDGKVRAERVSNEVNAYTYCLVKSA*

>P1;T1147
sequence:T1147:::::::0.00: 0.00
GPLGSDDPEPFDPKVVTYEIFGTPGAVVDINYLDLDARTQRVNDVTLPWSITLSTTAPSALAHIVAQGNADHIGC
RIIVDGELRVESVSTGVNAQTYCIEKSA*

