>P1;4ehx_A
structureX:4ehx_A:5:A:315:A:::-1.00:-1.00
SLLPFSYLYEKIINFRNTLYDKGFLKIKK-LPVPVISVGNLSVGGSGKTSFVMYLADLLKD--KRVCILSRGYKR
KSKGTLIVSEYGNLKVSW-----------EEAGD--EPYLMAKLLPHVSV---------VASEDRYKGGLLAL--
-EKLSPEVFILDDGFQHR-KLHRDLNILLLKKKDL-KDRLLPAGNLREPLKEIRRADALVLTYQE--VEPFE--F
FT----GKPTFKMFREFCCLLNSDFEEVPFDILKEREVIAFSGL--GDNGQFRKVL-KNLGIKVKEFMSFPDHYD
YSDFTPEE-------GEIYLT----TPKDLIKLQGY---ENVFALNFKVKLERE--EKLKKLIYRI---------
---FY*

>P1;test_target
sequence:test_target:::::::0.00: 0.00
RFRIASIVLKEGAVYQGADFKFEPLTEYDVLEKPSIKIIG-TGKRIGKTAVSAYAARVIHKHKYNPCVVAMGRGG
PREPEIVEGN--KIEITAEYLLEQADKGVHAASDHWEDALMS----RILTVGCRRCGGGMLGDTFITNVKRGAEI
ANKLDSDFVIMEGSGAAIPPVKTNRQIVTVGANQPMININNFFGP-----FRIGLADLVIITMCEEPMATTEKIK
KVEKFIKEINPSANVIPTVFR-----PKPVGNVEGKKVLFATTAPKVVVGKLVNYLESKYGCDVVG---VTPHLS
NRPLLRRDLKKYINKADLMLTELKAAAVDVATRVAIEAGLDVVYCDNIPVVIDESYGNIDDAIIEVVEMAIDDFK
NNR--*

