>P1;4ehx_A
structureX:4ehx_A:1:A:315:A:::-1.00:-1.00
MLRS-----------------------------------------------------------------------
-------------------------------SLLPFSYLYEKIINFRNTLYDKGFLKIKK-LPVPVISVGNLSVG
GSGKTSFVMYLADLLKD--KRVCILSRGYKRKSKGTLIVSEYGNLKVSW-----------EEAGD--EPYLMAKL
LPHVSV---------VASEDRYKGGLLAL---EKLSPEVFILDDGFQHR-KLHRDLNILLLKKKDL-KDRLLPAG
NLREPLKEIRRADALVLTYQE--VEPFE--FFT----GKPTFKMFREFCCLLNSDFEEVPFDILKEREVIAFSGL
--GDNGQFRKVL-KNLGIKVKEFMSFPDHYDYSDFTPEE-------GEIYLT----TPKDLIKLQGY---ENVFA
LNFKVKLERE--EKLKKLIYRI------------FY*

>P1;test_target
sequence:test_target:::::::0.00: 0.00
----MGETKKMICLVDGEHYFPVVKDSIEILDDLEHIDVVAVVFIGGTEKLQIEDPKEYSEKLGKPVFFGPDPKK
IPYDVIKKCVKKYNADIVMDLSDEPVVDYTKRFRIASIVLKEGAVYQGADFKFEPLTEYDVLEKPSIKIIG-TGK
RIGKTAVSAYAARVIHKHKYNPCVVAMGRGGPREPEIVEGN--KIEITAEYLLEQADKGVHAASDHWEDALMS--
--RILTVGCRRCGGGMLGDTFITNVKRGAEIANKLDSDFVIMEGSGAAIPPVKTNRQIVTVGANQPMININNFFG
P-----FRIGLADLVIITMCEEPMATTEKIKKVEKFIKEINPSANVIPTVFR-----PKPVGNVEGKKVLFATTA
PKVVVGKLVNYLESKYGCDVVG---VTPHLSNRPLLRRDLKKYINKADLMLTELKAAAVDVATRVAIEAGLDVVY
CDNIPVVIDESYGNIDDAIIEVVEMAIDDFKNNR--*
