>P1;6n9a_B
structureX:6n9a_B:1:B:198:B:::-1.00:-1.00
SNVLALDTSQR-IRIGLRKGEDL-FEISYTGEKKHAEILPVVVKKLLDELDLKVKDLDVVGVGIGPGGLTGLRVG
IATVVGLVSPYDIPVAPLNSFEMTAKSCPADGVVLVARRARKGYHYCAVYLKDKGLNPLKEPSVVSDEELEEITK
EFSPKIV---LKDD----------LLISPAVLVEESERLFREK-KTIHYYEIEPLYLQKSIAEL-*

>P1;6s84_C
structureX:6s84_C:1:C:198:C:::-1.00:-1.00
MNVLALDTSQR-IRIGLRKGEDL-FEISYTGEKKHAEILPVVVKKLLDELDLKVKDLDVVGVGIGPGGLTGLRVG
IATVVGLVSPYDIPVAPLNSFEMTAKSCPADGVVLVARRARKGYHYCAVYLKDKGLNPLKEPSVVSDEELEEITK
EFSPKIV---LKDD----------LLISPAVLVEESERLFREK-KTIHYYEIEPLYLQKSIAEL-*

>P1;2a6a_A
structureX:2a6a_A:1:A:193:A:::-1.00:-1.00
MNVLALDTS-QRIRIGLRKGED-LFEISYTGEKKHAEILPVVVKKLLDELDLKVKDLDVVGVGIGPGGLTGLRVG
IATVVGLVSPYDIPVAPLNSFEMTAKSCPADGVVLVARRARKGYHYCAVYLKDKGLNPLKEPSVVSDEELEEITK
EFSPKIV---LKDD----------LLISPAVLVEESERLFREK-KTIHYYEIEPLYLQK------*

>P1;T1183
sequence:T1183:::::::0.00: 0.00
MKILSIDTSFSFINFSVIEEEKVTFLHYLKSNKKTLELLPK----IFEELCIRPENFDAFAVSVGVGYLTSLRIG
VTFVKTWAYTLGKPVVSYKNLELLAKKTPVPFPKIPYLKVGSN-VFYQIFEES-S---SSEVKVFKGEELR----
--GYGISLKEFEDIKLGEKQFFHDIFPFSAYGGIYAYEFLKENPEGENVFEIEPIYVKPPYHVKD*
