>P1;3wj9_B
structureX:3wj9_B:3:B:411:B:::-1.00:-1.00
----QKSQFAYRSSKSIGLVNASENYASPPKFEAISE-PARNACYSPNGKLFAYATATQVVINDTESGAKLTQLP
AANTYELGFSPLGKYLSTWERPGKEADGTPKQ-----NMKVWNTETGQLVFSFVQRNQTGWNLQYTCDESLAARL
VTNEVHFYETGNMSKGPIAKLRVEGISDFALSPGQNHAVAVF-IPEKKGAPASVRTYSIPNFNSP---LSQKTFF
KADKVQFKWNALGTSLLVLTQTE-----KNYYGETN-----ITGQFDCRVDLDREGPIHDVCWNADSKEFGIVYG
YMPAKTAIFDNRANVVSIIPPAPRNTLIFSPNSRYILLAGFGNLQGSIDIFDAANNMKKITTVEAANCTYCEFSP
DSQFLLTAVTSPRLRVDNSIKIWHITGAPMFYEEF---NELYQAFWRPRPL------------------------
---------------------------------------------------------------------------
--------------------------------------------------------------------*

>P1;T1133
sequence:T1133:::::::0.00: 0.00
MAPSTPLLTVRGSEG-LYMVNGPPHFTESTVFPRESGKNCKVCIFSKDGTLFAWGNGEKVNIISVTNKGLLHSFD
LLKAVCLEFSPKNTVLATWQPYT----TSKDGTAGIPNLQLYDVKTGTCLKSFIQKKMQNWCPSWSEDETLCARN
VNNEVHFFENNNFNTI-ANKLHLQKINDFVLSPGPQPYKVAVYVPGSKGAPSFVRLYQYPNFAGPHAALANKSFF
KADKVTMLWNKKATAVLVIASTDVDKTGASYYGEQTLHYIATNGESAV-VQLPKNGPIYDVVWNSSSTEFCAVYG
FMPAKATIFNLKCDPVFDFGTGPRNAAYYSPHGHILVLAGFGNLRGQMEVWDVKNYKLISKPV-ASDSTYFAWCP
DGEHILTATCAPRLRVNNGYKIWHYTGSILHKYDVPSNAELWQVSWQPFLDGIFPAKTITYQAVPSEVPNEEPKV
ATAYRPPALRNKPITNSKLHEEEPPQNMKPQSGNDKPLSKTALKNQRKHEAKKAAKQEARSDKSPDLAPTPAPQS
TPRNTVSQSISGDPEIDKKIKNLKKKLKAIEQLKEQAATGKQLEKNQLEKIQKETALLQELEDLELGI*
